### ISSUE TITLE
Doesn't expand all goals

### ISSUE THREAD

**Issue by kamahen** [rla/rdet#2]
It appears that only the first deterministic goal in a body is expanded; others appear to be left unexpanded.

Here's a simple example. You can see that `t3` is not expanded in the first predicate (where `t3` is the 2nd goal) but is expanded in the second predicate.

```prolog
$ cat x.pl
:- use_module(library(rdet), [rdet/1]).

:- maplist(rdet, [t1/2, t2/2, t3/2]).

t1(A, B) :-
    t2(A, X),
    t3(X, B).

t2(A, B) :-
    t3(A, B).
/tmp$ swipl -q
1 ?- [x].
true.

2 ?- listing(t1).
t1(A, C) :-
    (   t2(A, B)
    ->  true
    ;   throw(error(goal_failed(t2/2, user:5)))
    ),
    t3(B, C).

true.

3 ?- listing(t2).
t2(A, B) :-
    (   t3(A, B)
    ->  true
    ;   throw(error(goal_failed(t3/2, user:9)))
    ).

true.
```

**Comment by kamahen** [comment]
(I'm not asking you to fix this; if you'll confirm that this is not intended behaviour then I'll try to fix it.)

**Comment by rla** [comment]
@kamahen, I have debugged it a bit and found that this is definitely a bug. I also noticed that there is no test case with multiple expanded call inside a predicate body. That would have likely caught it.

The issue is with https://github.com/rla/rdet/blob/f2e517ca61313ad9565d83c9bc03110cbd90b140/prolog/rdet.pl#L88 which actually refers to the whole predicate term, not the current goal term (it's not clear from the documention either). The goal marker is asserted and checked later to avoid re-expanding goals that have already expanded. t2 and t3 will have clashing goal markers in t1 and that's why t3 is not expanded.

We need some better way to track goals that have already been expanded. The expansion as a whole runs as a fixpoint operation, until nothing is expanded anymore. I current have no idea how to solve it.

**Comment by kamahen** [comment]
I've added a question at https://swi-prolog.discourse.group/t/how-to-get-to-a-fixed-point-with-goal-expansion/334

**Comment by kamahen** [comment]
Here's something that might work (I did a quick test of this and it *appears* to work on my little test).

Modify `goal_marker/2` to `goal_marker/3`:
```prolog
goal_marker(ContextModule, Goal, Marker):-
    prolog_load_context(term_position, Pos),
    stream_position_data(byte_count, Pos, Byte),
    format(atom(Aux), '__aux_det_~w ~q', [Byte, Goal]), % <===================
    Marker = ContextModule:Aux/0,
    debug(rdet, 'rdet: maker: ~q', [Marker]).
```

and change `try_rewrite/4` to:
```prolog
try_rewrite(Goal, ContextModule, Name, Arity, Out):-
    goal_marker(ContextModule, Goal, Marker), % <=================
    \+ current_predicate(Marker),
    Marker = _:Aux/0,
    compile_aux_clauses([Aux]),
    rewrite_goal(Goal, Name, Arity, ContextModule, Out).
```

This modification isn't perfect: if an identical goal appears twice in a term, then only the first one will be expanded -- but this seems an unlikely situation). Also, it's probably best to use `prolog_load_context(variable_names, ...)` to transform the uninstantiated variables in the goal to names (otherwise, we're depending on `expand_goal/2` to always use the same variables).

If this seems right, I can create a pull request for you.

**Comment by kamahen** [comment]
SWI-Prolog 8.1.3 has changed how it detects fixed point; the test for `current_predicate(Marker)` is no longer needed (I've tested this with some of my code).

**Comment by rla** [comment]
I'm linking related topics from SWI-Prolog discussions:

 * <https://groups.google.com/forum/#!topic/swi-prolog/WlMSFODGJ1Q/discussion>
 * <https://swi-prolog.discourse.group/t/how-to-get-to-a-fixed-point-with-goal-expansion/334>

The first one has an idea to generate a wrapper to the called predicate instead of wrapping the call. With stack traces enabled, this might be enough diagnose runtime det check failures. It might be worth exploring the use of this idea in this library (to add a 2nd mode of rewriting goals for example).

I'm going to leave in `current_predicate` check for now because of backwards compatibility with older installations but I will look for solutions to support everything, possibly using version-specific conditional compilation.

**Comment by rla** [comment]
Linking to #5.

**Comment by rla** [comment]
A version with wrapping predicates is in the branch https://github.com/rla/rdet/tree/wrap_with_aux_goal

This seems to also lead to cleaner code. Benchmarks are not bad.

Old version:

```
make benchmark
swipl -s benchmark/benchmark-rdet.pl -g benchmark,halt -t 'halt(1)'
Insertion sort benchmark of 3000 items with rdet annotations.
% 9,003,004 inferences, 1.063 CPU in 1.071 seconds (99% CPU, 8473416 Lips)
swipl -s benchmark/benchmark-vanilla.pl -g benchmark,halt -t 'halt(1)'
Insertion sort benchmark of 3000 items without rdet annotations.
% 9,003,002 inferences, 1.969 CPU in 2.480 seconds (79% CPU, 4572953 Lips)
swipl -O -s benchmark/benchmark-rdet.pl -g benchmark,halt -t 'halt(1)'
Insertion sort benchmark of 3000 items with rdet annotations.
% 4,504,504 inferences, 0.906 CPU in 0.924 seconds (98% CPU, 4970487 Lips)
swipl -O -s benchmark/benchmark-vanilla.pl -g benchmark,halt -t 'halt(1)'
Insertion sort benchmark of 3000 items without rdet annotations.
% 4,504,502 inferences, 1.828 CPU in 2.341 seconds (78% CPU, 2464001 Lips)
```

With wrapping predicates:

```
make benchmark
swipl -s benchmark/benchmark-rdet.pl -g benchmark,halt -t 'halt(1)'
Insertion sort benchmark of 3000 items with rdet annotations.
% 13,507,506 inferences, 1.125 CPU in 1.140 seconds (99% CPU, 12006672 Lips)
swipl -s benchmark/benchmark-vanilla.pl -g benchmark,halt -t 'halt(1)'
Insertion sort benchmark of 3000 items without rdet annotations.
% 9,003,002 inferences, 1.875 CPU in 2.498 seconds (75% CPU, 4801601 Lips)
swipl -O -s benchmark/benchmark-rdet.pl -g benchmark,halt -t 'halt(1)'
Insertion sort benchmark of 3000 items with rdet annotations.
% 9,009,006 inferences, 0.984 CPU in 0.989 seconds (99% CPU, 9152006 Lips)
swipl -O -s benchmark/benchmark-vanilla.pl -g benchmark,halt -t 'halt(1)'
Insertion sort benchmark of 3000 items without rdet annotations.
% 4,504,502 inferences, 1.859 CPU in 2.340 seconds (79% CPU, 2422589 Lips)
```

**Comment by rla** [comment]
With the new rewrite scheme, the original test file is expanded to:

```prolog
t1(A, C) :-
    '__aux_det_user;t2'(A, B),
    '__aux_det_user;t3'(B, C).

t2(A, B) :-
    '__aux_det_user;t3'(A, B).

'__aux_det_user;t2'(A, B) :-
    (   t2(A, B)
    ->  true
    ;   throw(error(goal_failed(t2/2), _))
    ).

'__aux_det_user;t3'(A, B) :-
    (   t3(A, B)
    ->  true
    ;   throw(error(goal_failed(t3/2), _))
    ).
```

**Comment by rla** [comment]
The issue has completely gone away after switching to `wrap_predicate`. We are not using goal markers anymore.
