### ISSUE TITLE
Explore different goal expansion schemes

### ISSUE THREAD

**Issue by rla** [rla/rdet#5]
There seem to be 3 possible goal expansion schemes:

 1. Rewrite call. This is currently done. It has issues with expanding
  the same goal again but has good performance.
 2. Rewrite call into an aux goal per call site. This seems to be currently impossible
  as we don't have enough information about call sites to generate the aux goal name.
 3. Rewrite call into an aux goal. All calls to the same predicate will call the aux predicate.
  This feels like the most sane option but might suffer from worse error reporting and
  performance than (1).

**Comment by kamahen** [comment]
I'm a bit confused by your list of possibilities. Here's what I thought would be the simplest way:

```prolog
my_pred(X,Y,Z) :- ...
my_pred(A,B,C) :- ...
```
gets transformed to 
```prolog
my_pred(X1,X2,X3) :- ( rdet_my_pred(X1,X2,X3) -> true ; throw(error(goal_failed(my_pred(X1,X2,X3), _)) ).
rdet_my_pred(X,Y,Z) :- ...
rdet_my_pred(A,B,C) :- ...
```

This approach can be generalized into a kind of "batch" trace facility, which I would find very useful (e.g., show call/result for some predicates, when it's impractical to use the interactive trace facilities). See also discussion https://swi-prolog.discourse.group/t/spy-on-condition/524 which could be easily done with this kind of expansion.

**Comment by kamahen** [comment]
(I've edited my last comment: `s/my_goal/my_pred/g`)

A generalized wrapper functionality would be very useful. There are a number of variants:
1. rdet (if the predicate fails, throw an exception)
2. rdet_plus (if the predicate fails or if it leaves a choicepoint, throw an exception)
3. A call trace (print a message on entry to a predicate)
4. A result trace (print a message on exit from a predicate, and also a message if the predicate fails)
5. #3 or #4 with a condition
6. [Add your favourite batch debug desire here.]

#3 is easy to do without rdet &mdash; merely add a clause at the beginning that does a print + fail. But it's often useful to see the results, so a more general wrapper helps.

I find that interactive tracing isn't very useful because I'm often debugging complex data structures, or having to run a lot of code before the specific situation occurs; so being able to selectively trace or print is very useful. (it's also useful to be selective with the output; sometimes portray/1 is enough but sometimes it's a matter of which arguments to print)

**Comment by rla** [comment]
> I'm a bit confused by your list of possibilities. Here's what I thought would be the simplest way

That would be the 4th way! The only issue here I see is renaming the original predicate or rather a way to do it reliably. This must also support `make`. I think that `copy_predicate_clauses/2` might work. And to support `make`, using `compile_aux_clauses` should work. This approach has benefit that it does not generate so much noise in listing/debugger.

> I find that interactive tracing isn't very useful

True! "The most effective debugging tool is still careful thought, coupled with judiciously placed print statements." (Brian Kernighan)

Anyway, considering declarative tracing, have you explored the use of http://www.swi-prolog.org/pldoc/doc_for?object=prolog_trace_interception/4

**Comment by rla** [comment]
The library uses now `wrap_predicate` instead of expansion. Any custom tracing can be built directly on top of `wrap_predicate` (it is much less verbose than expansion and much easier to use). This library will only do "non-failure" check.
