### ISSUE TITLE
Build wrapping on top of wrap_predicate/4

### ISSUE THREAD

**Issue by rla** [rla/rdet#7]
Current scheme uses tricky rewriting/expansion of predicate goals inside other predicate bodies. Using the built-in wrap_predicate/4 should make it a bit more reliable.

Link to documentation:
<https://www.swi-prolog.org/pldoc/doc/_SWI_/library/prolog_wrap.pl>

Discussion from SWI Discourse:
<https://swi-prolog.discourse.group/t/wrapping-predicates/668>

**Comment by kamahen** [comment]
I've run into a problem when a predicate is used multiple times in a clause - the same "aux" predicate is generated for each call, so there's a "discontiguous predicate" warning, not to mention the duplicate definitions which will cause unnecessary choice points (which will get pruned away at run-time by the if-then-else). Using wrap_predicate solves this problem also.

**Comment by rla** [comment]
I published version 1.0.0 that builds on top of `wrap_predicate`. Everything is backwards compatible except exact error terms that now miss source location. Source location is reported by the built-in error reporting now.

**Comment by kamahen** [comment]
One catch with using `wrap_predicate` -- it won't wrap some imported predicates, such as `aggregate:aggregate_all/3'.

I also get warnings such as `Local definition of pykythe:base64_term/2 overrides weak import from pykythe_utils` ... I'm guessing that this is because I put all the `rdet/1` declarations in my main file and they now be in the places where the predicates are defined.
